version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      -run: 
      command: |
          pip install docker-compose
          docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"