jobs:
  build:
    docker:
      - image: buildpack-deps:trusty


    run: pip install docker-compose

    run:
      - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"