version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      -run: 
      command: |
          pip install docker-compose
          docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"