jobs:
  build: # name of your job
    docker: # executor type
      - image: buildpack-deps:alpine:3.13 # primary container will run Ubuntu Trusty

    steps:
      -run: 
        docker-compose.yml up,
        docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"