version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python 3.7
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            pip install docker-compose
            docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
            
      
      

          