jobs:
  build: # name of your job
    docker: # executor type
      - image: buildpack-deps:alpine # primary container will run Ubuntu Trusty

    steps:
      run: 
        -pip install docker-compose,

        - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"